### PR TITLE
First design change

### PR DESCRIPTION
**Pull request by Sheshank-s**
first design change

preview: https://scratchuserstats.github.io/ScratchStats-V3/

### CODE REVIEW

**Comment by Sheshank-s** [comment]
Also lets move the project to the scratchuserstats repo

**Comment by WorldLanguages** [comment]
I will see this later today, but I can confirm we won't be using cors.io for now. The school PC I'm on has Avast and apparently cors.io is a phishing website.

**Comment by Sheshank-s** [comment]
okay lol, once you do how are we going to move this to the scratchuserstats repo?

**Comment by Sheshank-s** [comment]
@WorldLanguages Can you merge lmao

**Comment by WorldLanguages** [comment]
Hi sorry for the delay.
1) We won't be using cors.io for now
2) imo, the current font and background color look better
3) Browser logos are cool, but you haven't taken into account this:
image
4) Header in my phone looks worse. Buttons are tiny and ceebee's logo's top part overflows

**Comment by Sheshank-s** [comment]
I think it looks much better, I can change the cors.io though. Header is fine on mobile

**Comment by WorldLanguages** [comment]
https://i.imgur.com/Kzcpo8y.png

**Comment by Sheshank-s** [comment]
Okay if i change that and the cors will you merge it.

**Comment by moeenio** [comment]
@GreenBayRules Use the same font size as the rest of text for buttons. Also, maybe using the Scratch's S instead of the full logo for the Scratch URL button ?

**Comment by moeenio** [comment]
https://raw.githubusercontent.com/LLK/scratch-www/develop/static/favicon.ico

**Comment by moeenio** [comment]
@GreenBayRules Also you should credit flaticon, and have the icons in your project directly

**Comment by Sheshank-s** [comment]
That's a good idea, thanks! I will do all of this by the end of the day

**Comment by Sheshank-s** [comment]
lol i kinda forgot im doing it now

**Comment by Sheshank-s** [comment]
Okay removed cors

**Comment by Sheshank-s** [comment]
Okay so last step is just making the statistic rows responsive, then you can merge it

**Comment by Sheshank-s** [comment]
oh and crediting flaticon and the browser logo thing

**Comment by Sheshank-s** [comment]
Also, what do you think of changing the join date from "Sat, Sep 15, 1949, 7:32:33 AM" to just "Sep 15, 1949" or like "Sep 15, 1949, 7:32 AM"

**Comment by Sheshank-s** [comment]
Ok im working on it ill try and finish it tomm.

world please review what i've done so far, just note im still working on the stat rows.

**Comment by Sheshank-s** [comment]
@WorldLanguages

**Comment by Sheshank-s** [comment]
@WorldLanguages i think its ready to merge

**Comment by WorldLanguages** [comment]
@GreenBayRules Sup! I don't really like this new "blue" and I'm not sure about the font, but the rest is mostly good improvement. Can you keep the colors and fonts as they are on ScratchStats.com at the moment?

**Comment by Sheshank-s** [comment]
Are you sure... i mean i think this new blue looks really good, it also matches with scratch... 

about the font, the font matches well with the site, Montserrat font is really over used and makes the website look really idk childish. 

Do you think maybe we should take a vote or something idk. 

image
image


to me it seems like the new one looks way better..

**Comment by Sheshank-s** [comment]
i mean switching back to the old font doesn't make too much of a difference:
image
but i think roboto is more like clean

**Comment by moeenio** [comment]
Go to top button appearance seems to depend on wich platform you're using. On OS X it looks like that :
Screenshot_2019-05-24 ScratchStats com

**Comment by Sheshank-s** [comment]
Ew, I didn't notice that. Thanks for bringing that up, I'll fix that now.

**Comment by Sheshank-s** [comment]
@WorldLanguages What do you think?

**Comment by Sheshank-s** [comment]
Bruh...

**Comment by Sheshank-s** [comment]
@WorldLanguages Respond! Why do you act as if you didn't get any message lol

**Comment by WorldLanguages** [comment]
@GreenBayRules I tried to reach you via Snapchat. If you want this merged, it will probably require many little changes and it makes more sense to talk somewhere else.

**Comment by Sheshank-s** [comment]
My parents dont let me use snapchat anymore. would you be okay with texting?

**Comment by WorldLanguages** [comment]
@GreenBayRules Please:
- Use the same blue and font as current master.
- Keep native emojis (heart, star, etc.) and remove flaticon.com from footer.
- For now, remove the browser logo. We will work on that after merge.
- Keep flags in "shiny". We can discuss if "flat" is better after merge.
- Keep button names as in current master (for example, "Scratch URL" → "go to Scratch profile").
- Make griffpatch default user

**Comment by Sheshank-s** [comment]
- Use the same blue and font as current master. 
Okay I guess, although its kind of ugly
- Keep native emojis (heart, star, etc.) and remove flaticon.com from footer.
The point of this is so that it works on all OS. on Linux it looks really ugly. Crediting flaticon isn't a big deal
- For now, remove the browser logo. We will work on that after merge.
Okay sure
- Keep flags in "shiny". We can discuss if "flat" is better after merge.
well flat goes more with the theme
- Keep button names as in current master (for example, "Scratch URL" → "go to Scratch profile").
No, that makes the button too long
- Make griffpatch default user
Okay i guess

The problem is is that the reason why the current site doesn't look good is because there isn't like one design theme throughout the page:
image
image
I keep looking at them together, and I still don't see how you don't like the different colors and fonts. It just looks so much better to me

**Comment by Sheshank-s** [comment]
Montserrat font is looked down upon a lot as well...
THe mobile design for the new one is way better than the current one too.

**Comment by Sheshank-s** [comment]
Also sorry for the super late response i was in australia for like a month.

**Comment by Sheshank-s** [comment]
Maybe we should get a group of like 10  people idk and have a vote between the two designs.

**Comment by moeenio** [comment]
> I keep looking at them together, and I still don't see how you don't like the different colors and fonts. It just looks so much better to me

Well that's personal. I quite like the color.

**Comment by Sheshank-s** [comment]
@locness3 Its not personal, I made both the designs..

**Comment by Sheshank-s** [comment]
I'm fine changing the colors and font if necessary ig though

**Comment by moeenio** [comment]
I mean that's what you think but I like the current color.

**Comment by moeenio** [comment]
Also, this shows if the browser is unknown
Screenshot_2019-07-13 ScratchStats com

**Comment by WorldLanguages** [comment]
@GreenBayRules Please undo the changes I mentioned before, so I can merge

**Comment by Sheshank-s** [comment]
Alright ill do it on the weekend very busy during weekdays

**Comment by GreenBayRules** [comment]
@WorldLanguages  I'd like to talk to you about some ideas if you want, I created a slack for us to talk: https://join.slack.com/t/scratchstats/shared_invite/enQtNzAzOTE5ODE5MTQzLWUxYzk3YzNmMTk2YzA2ODhjYjYzOGQyNzY4ZjllMjUzYzc1Y2YyMDhiMGJjZGQ4ZGNlOTBjM2Y2OWE1MTJkNjE

**Comment by Sheshank-s** [comment]
Why?

**Comment by moeenio** [comment]
Why did you close @WorldLanguages ?????

**Comment by Sheshank-s** [comment]
i think he got mad cuz of this https://scratch.mit.edu/users/world_languages/#comments-62123764

**Comment by moeenio** [comment]
oof

**Comment by WorldLanguages** [comment]
You had almost 3 months to implement the changes I mentioned. I'll be doing modifications to the site soon and won't deal with merge conflicts. I do not like polls on my profile either, if you prefer your design feel free to fork the website, it's open source after all. You don't even need your own domain, I can give you a *.scratchstats.com subdomain for free if you want.

**Pull request closed without merging**
